### Alias ###
alias h='history'
alias gs="git status"
alias gitk='gitk 2>/dev/null' # fix for xcode error with gitk

# rails
alias migrate="bundle exec rake db:migrate && bundle exec rake db:migrate RAILS_ENV=test"

# ssh
alias aws="ssh ec2-user@ec2-23-20-13-68.compute-1.amazonaws.com"
alias aws2="ssh -i ~/.ssh/rake2.pem ubuntu@ec2-50-17-94-49.compute-1.amazonaws.com"
alias aws3="ssh -i ~/.ssh/test.pem ec2-user@ec2-54-224-29-105.compute-1.amazonaws.com"

# vim
alias vim="mvim"

# storage
alias redis="redis-server /usr/local/etc/redis.conf" 
alias my="mysql -u root"

### Settings ###
NO_COLOR='\e[0m' #disable any colors
EBLACK='\e[1;30m'
RAILS_ENV="development"

PS1="\n\u:\w \[$EBLACK\]\$(vcprompt)\[$NO_COLOR\] \n$ "

function take() { 
    mkdir -p "$1"
    cd "$1" 
}
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

# bash history
export HISTCONTROL=ignoredups:erasedups
export HISTSIZE=10000                
export HISTFILESIZE=10000           
shopt -s histappend

# Save and reload the history after each command finishes
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

### Paths ###
export PATH=$HOME/bin:/usr/local/bin:/usr/local/mysql/bin:$PATH
export PATH="/usr/local/heroku/bin:$PATH"
export MANPATH=`/usr/bin/manpath`
export BUNDLER_EDITOR="/usr/local/bin/mvim"
export ANDROID_HOME="/usr/local/Cellar/android-sdk/24.0.2"
export SCRAPE_BOX="true"

eval "$(rbenv init -)"
